# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20170409_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choise',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='choise_type',
            options={'verbose_name': 'Тип ответа', 'verbose_name_plural': 'Типы ответов'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='choise',
            name='owner',
        ),
        migrations.AlterField(
            model_name='choise',
            name='choice_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
